function numdems
%NUMDEMS For setting up numeric computation demos from the MATLAB DEMO.

%   Ned Gulley, 6-21-93
%   Copyright (c) 1984-98 by The MathWorks, Inc.
%   $Revision: 5.8 $  $Date: 1997/11/21 23:26:39 $

labelList=str2mat( ...
        'Spectral Analysis', ...
        'Census Example', ...
        'Graphics Input', ...
        'ODEs', ...
        'Quadrature', ...
        'Zerofinding', ...
        'Function Plot', ...
        'Earthquake Example');

nameList=str2mat( ...
        'fftdemo', ...
        'census', ...
        'spline2d', ...
        'lotkademo', ...
        'quaddemo', ...
        'zerodemo', ...
        'fplotdemo', ...
        'quake');

cmdlnwin(labelList,nameList);
