SELECT TOP 5 * FROM table_name;
SELECT TOP 20 PERCENT * FROM table_name;
SELECT * FROM table_name LIMIT 10;
SELECT * FROM table_name WHERE ColumnName1 LIKE '%th%';
SELECT * FROM table_name WHERE ColumnName2 NOT LIKE '%s';
SELECT * FROM table_name WHERE ColumnName3 LIKE '_alue';
SELECT * FROM table_name WHERE ColumnName4 LIKE 'co_t_nue';
SELECT * FROM table_name WHERE ColumnName1 LIKE '[abc]%';
SELECT * FROM table_name WHERE ColumnName2 LIKE '[a-f]%';
SELECT * FROM table_name WHERE ColumnName3 LIKE '[!abc]%';
SELECT * FROM table_name WHERE ColumnName3 NOT LIKE '[abc]%';
SELECT * FROM table_name WHERE ColumnName4 IN (1, 2, 3, 4);
SELECT * FROM table_name WHERE ColumnName4 IN ('query', 'word', 'elf', 'ribbon');
SELECT * FROM table_name WHERE ColumnName4 BETWEEN 10 AND 20;
SELECT * FROM table_name WHERE (ColumName4 BETWEEN 'C' AND 'G') AND NOT ColumnNameID IN (1, 2, 3);
SELECT * FROM table_name WHERE ColumnName5 NOT BETWEEN 0 AND 99;
SELECT * FROM table_name WHERE ColumnName6 BETWEEN #01/01/1999# AND #01/01/2000#;
SELECT ColumnName1 AS CN1, ColumnName2 AS [CN 2] FROM table_name;
SELECT ColumnName1, ColumnName2 + ', ' + ColumnName3 + ', ' + ColumnName4 AS CNs FROM table_name;
SELECT a.ColumnName1, a.ColumnName2, b.ColumnName1 FROM alpha_table_name AS a, beta_table_name AS b WHERE b.ColumnName1 = a.ColumnName1;
